project_id: local-project

triggers:
  - name: gcs-object-finalize
    source: pubsub
    topic: gcs-notifications
    filters:
      event_type: google.cloud.storage.object.v1.finalized
      # object_prefix: uploads/
    targets:
      - type: cloudevent
        url: http://echo-function:8080
        method: POST
